In [1]:
import requests
import json
import re
import numpy as np
import pandas as pd

In [3]:
def get_year(year):
    meet = requests.get(year).text
    meet = meet.split("Event ")
    return meet

sex = "Men "
course = "Yard "

yr2007 = get_year("http://meetresults.com/2007/eisl/results.html")
yr2008 = get_year("http://meetresults.com/2008/eisl/results.html")
yr2009 = ""
yr2010 = get_year("http://www.pennathletics.com//pdf8/731145.pdf")
yr2011 = get_year("http://meetresults.com/2011/ivies/results.html")
yr2012 = get_year("http://www.goprincetontigers.com/ViewArticle.dbml?DB_OEM_ID=10600&ATCLID=205391399")
yr2013 = get_year("http://www.ivyleaguesports.com/championships/mswimdive/2012-13/2013_Ivy_Complete_Meet.htm")
yr2014 = get_year("http://www.ivyleaguesports.com/championships/mswimdive/2013-14/results-splits.html")
yr2015 = get_year("http://www.ivyleaguesports.com/championships/mswimdive/2014-15/results-final.htm")
# yr2016 = get_year("")

In [4]:
def separate_events(year):
    new_list = []
    for event in year:
        if "Time Trial" not in event:
            if "Relay" not in event:
                if "Swim-off" not in event:
                    if "Points" in event:
                        new_list.append(event)
    return new_list

events = separate_events(yr2007)
print(type(events))
print(len(events))
for event in events:
    print(event.split("\n")[0])
    
print(events[6][:200])

<class 'list'>
16
2  Men 500 Yard Freestyle</b>
3  Men 200 Yard IM</b>
4  Men 50 Yard Freestyle</b>
5  Men 1 mtr Diving</b>
8  Men 1000 Yard Freestyle</b>
9  Men 400 Yard IM</b>
10  Men 100 Yard Butterfly</b>
11  Men 200 Yard Freestyle</b>
12  Men 100 Yard Breaststroke</b>
13  Men 100 Yard Backstroke</b>
15  Men 1650 Yard Freestyle</b>
16  Men 200 Yard Backstroke</b>
17  Men 100 Yard Freestyle</b>
18  Men 200 Yard Breaststroke</b>
19  Men 200 Yard Butterfly</b>
20  Men 3 mtr Diving</b>
10  Men 100 Yard Butterfly</b>
===============================================================================
 Meet Record: M 47.10        2003 Jesse Gage (Princeton)
 EISL

In [6]:
def split_event_by_line(string):
    if "Points" in string:
        string = string.split("Points")[1]
        string = string.replace("\r","")
        if "Bradley\n" in string:
            string = string.replace("Bradley\n", "Bradley")
        list_of_strings = string.split("\n")
        return list_of_strings


lol = split_event_by_line(events[4])
print(type(lol))
print(len(lol))
print(lol[3])
print("")
lol

<class 'list'>
31
  2 Griest, Robert            SO Princeton                      9:06.64N  28

[' ',
 '===============================================================================',
 '  1 Wollner, Samuel           JR Harvard                        9:06.36N  32  ',
 '  2 Griest, Robert            SO Princeton                      9:06.64N  28  ',
 '  3 Ashley, Dave              SR Princeton                      9:08.61N  27  ',
 '  4 Lynch, Eric               SO Harvard                        9:10.18N  26  ',
 '  5 Fog, Henning              JR Columbia                       9:12.40N  25  ',
 '  6 Volosin, Peter            JR Brown                          9:15.52N  24  ',
 '  7 Meyer, Alex               FR Harvard                        9:17.08N  23  ',
 '  8 Brunnick, Mason           FR Harvard                        9:17.20N  22  ',
 '  9 Buncher, Stan             JR Princeton                      9:19.88N  20  ',
 ' 10 Ellis, Kevin              SO Dartmouth                      9:21.07N  17  ',
 ' 11 Abbott, Jake              SR Columbia                       9:21.48N  15.5',
 ' 11 Fee, James                FR Pennsylvania                   9:21.48N  15.5',
 ' 13 Reeb, Cody                FR Navy                           9:26.39   14  ',
 ' 14 Gray, Thomas              FR Harvard                        9:27.76   13  ',
 ' 15 Cochran, Nick             SO Cornell                        9:28.07   12  ',
 ' 16 Garber, Kent              SR Yale                           9:29.79   11  ',
 ' 17 Hutchinson, Jack          SR Yale                           9:31.13    9  ',
 ' 18 McGrath, Jason            SR Pennsylvania                   9:31.44    7  ',
 ' 19 Cousins, Sebastian        SO Yale                           9:33.27    6  ',
 ' 20 Diehl, Porter             SO Dartmouth                      9:37.65    5  ',
 ' 21 Braunreuther, Joe         JR Dartmouth                      9:38.12    4  ',
 ' 22 Guthmann, David           SO Navy                           9:38.21    3  ',
 ' 23 Thompson, Brandon         SR Pennsylvania                   9:45.52    2  ',
 ' 24 Curran, Jack              FR Navy                           9:48.58    1  ',
 ' 25 Glenn, Rob                JR Brown                          9:48.99  ',
 ' 26 Andres, Josh              JR Navy                           9:52.63  ',
 ' 27 Stathopoulos, Cary        FR Dartmouth                      9:55.40  ',
 ' ',
 '<b>']

In [10]:
line = " 12 O'Mara, Michael           SR Brown                1:52.89    1:52.63   15  \r"
print(type(line))

def extract_rank_from_line(line):
    try:
        return int(line[:4])
    except ValueError:
        return 0

def extract_name_from_line(line):
    comma = re.search(r'\,', line).start()
    last_name = line[comma::-1].split(" ")[0][::-1]
    first_name = line[comma+2:].split(" ")[0]
    name = last_name + " " + first_name
    return name

def extract_year_from_line(line):
    years = [" FR ", " SO ", " JR ", " SR "]
    for year in years:
        if year in line:
            return year.replace(" ", "")
        if not any(yr in line for yr in years):
            ix = re.search(r'\d', line[6:]).start()
            return line[ix+6:ix+8]

def extract_school_from_line(line):
    years = [" FR ", " SO ", " JR ", " SR "]
    for year in years:
        if year in line:
            school = line.split(year)[1]
            school = school.split(" ")[0]
            return school
        if not any(yr in line for yr in years):
            return "NA"

def extract_times_from_line(line):
    time1 = re.compile(r'\d*\:\d\d\.\d\d')
    line_ix = [(m.start(0), m.end(0)) for m in re.finditer(time1, line)]
    if len(line_ix) == 2:
        p_start = line_ix[0][0]
        p_end = line_ix[0][1]
        f_start = line_ix[1][0]
        f_end = line_ix[1][1]
        prelims = line[p_start:p_end]
        finals = line[f_start:f_end]
    elif len(line_ix) == 1:
        f_start = line_ix[0][0]
        f_end = line_ix[0][1]
        finals = line[f_start:f_end]
        prelims = "N/A"
    elif len(line_ix) == 0:
        time2 = re.compile(r'\d\d\.\d\d')
        line_ix = [(m.start(0), m.end(0)) for m in re.finditer(time2, line)]
        p_start = line_ix[0][0]
        p_end = line_ix[0][1]
        f_start = line_ix[1][0]
        f_end = line_ix[1][1]
        prelims = line[p_start:p_end]
        finals = line[f_start:f_end]
    return [prelims, finals]

def extract_points_from_line(line):
    try: 
        return float(line[-5:])
    except ValueError:
        return 0

def extract_data_from_line(line):
    rank = extract_rank_from_line(line)
    if rank:
        name = extract_name_from_line(line)
        year = extract_year_from_line(line)
        school = extract_school_from_line(line)
        prelim = extract_times_from_line(line)[0]
        final = extract_times_from_line(line)[1]
        points = extract_points_from_line(line)
        return [rank, name, year, school, prelim, final, points]

def extract_all_data_from_event(event):
    list_of_lines = split_event_by_line(event)
    nlist = []
    for line in list_of_lines:
        if line:
            d = extract_data_from_line(line)
            if d:
                nlist.append(d)
    return nlist

extracted_event = extract_all_data_from_event(events[4])
extracted_event

<class 'str'>

[[1, 'Wollner, Samuel', 'JR', 'Harvard', 'N/A', '9:06.36', 32.0],
 [2, 'Griest, Robert', 'SO', 'Princeton', 'N/A', '9:06.64', 28.0],
 [3, 'Ashley, Dave', 'SR', 'Princeton', 'N/A', '9:08.61', 27.0],
 [4, 'Lynch, Eric', 'SO', 'Harvard', 'N/A', '9:10.18', 26.0],
 [5, 'Fog, Henning', 'JR', 'Columbia', 'N/A', '9:12.40', 25.0],
 [6, 'Volosin, Peter', 'JR', 'Brown', 'N/A', '9:15.52', 24.0],
 [7, 'Meyer, Alex', 'FR', 'Harvard', 'N/A', '9:17.08', 23.0],
 [8, 'Brunnick, Mason', 'FR', 'Harvard', 'N/A', '9:17.20', 22.0],
 [9, 'Buncher, Stan', 'JR', 'Princeton', 'N/A', '9:19.88', 20.0],
 [10, 'Ellis, Kevin', 'SO', 'Dartmouth', 'N/A', '9:21.07', 17.0],
 [11, 'Abbott, Jake', 'SR', 'Columbia', 'N/A', '9:21.48', 15.5],
 [11, 'Fee, James', 'FR', 'Pennsylvania', 'N/A', '9:21.48', 15.5],
 [13, 'Reeb, Cody', 'FR', 'Navy', 'N/A', '9:26.39', 14.0],
 [14, 'Gray, Thomas', 'FR', 'Harvard', 'N/A', '9:27.76', 13.0],
 [15, 'Cochran, Nick', 'SO', 'Cornell', 'N/A', '9:28.07', 12.0],
 [16, 'Garber, Kent', 'SR', 'Yale', 'N/A', '9:29.79', 11.0],
 [17, 'Hutchinson, Jack', 'SR', 'Yale', 'N/A', '9:31.13', 9.0],
 [18, 'McGrath, Jason', 'SR', 'Pennsylvania', 'N/A', '9:31.44', 7.0],
 [19, 'Cousins, Sebastian', 'SO', 'Yale', 'N/A', '9:33.27', 6.0],
 [20, 'Diehl, Porter', 'SO', 'Dartmouth', 'N/A', '9:37.65', 5.0],
 [21, 'Braunreuther, Joe', 'JR', 'Dartmouth', 'N/A', '9:38.12', 4.0],
 [22, 'Guthmann, David', 'SO', 'Navy', 'N/A', '9:38.21', 3.0],
 [23, 'Thompson, Brandon', 'SR', 'Pennsylvania', 'N/A', '9:45.52', 2.0],
 [24, 'Curran, Jack', 'FR', 'Navy', 'N/A', '9:48.58', 1.0],
 [25, 'Glenn, Rob', 'JR', 'Brown', 'N/A', '9:48.99', 0.99],
 [26, 'Andres, Josh', 'JR', 'Navy', 'N/A', '9:52.63', 0.63],
 [27, 'Stathopoulos, Cary', 'FR', 'Dartmouth', 'N/A', '9:55.40', 0.4]]

In [11]:
def get_event_name_num(event):
    if "Diving" not in event:
        try:
            event_num = int(event[:2])
        except ValueError:
            event_num = "NaN"
        dist = int(event.split(sex)[1].split(" ")[0])
        stroke = event.split(course)[1].split("<")[0]
        if (type(event_num) == int) and event_num < 25:
            return event_num, dist, stroke
    else:
        try:
            event_num = int(event[:2])
        except ValueError:
            event_num = "NaN"
        dist = int(event.split(sex)[1].split(" ")[0])
        stroke = "Diving"
        if (type(event_num) == int) and event_num < 25:
            return event_num, dist, stroke

        
for event in events:
    print(get_event_name_num(event))

(2, 500, 'Freestyle')
(3, 200, 'IM')
(4, 50, 'Freestyle')
(5, 1, 'Diving')
(8, 1000, 'Freestyle')
(9, 400, 'IM')
(10, 100, 'Butterfly')
(11, 200, 'Freestyle')
(12, 100, 'Breaststroke')
(13, 100, 'Backstroke')
(15, 1650, 'Freestyle')
(16, 200, 'Backstroke')
(17, 100, 'Freestyle')
(18, 200, 'Breaststroke')
(19, 200, 'Butterfly')
(20, 3, 'Diving')

In [12]:
def pandize_meet(year):
    meet_results = pd.DataFrame(columns = ["Ev#", "Distance", "Stroke", "Rank", "Name", "Yr", "School", "Prelim", "Final", "Points"])

    events_list = separate_events(year)    
    for event in events_list:
        event_name_num = get_event_name_num(event)
        print(event_name_num)
        event_data = extract_all_data_from_event(event)
        pandized_event = pd.DataFrame(event_data)
        pandized_event.columns = ["Rank", "Name", "Yr", "School", "Prelim", "Final", "Points"]
        pandized_event["Ev#"] = event_name_num[0]
        pandized_event["Distance"] = event_name_num[1]
        pandized_event["Stroke"] = event_name_num[2]
        meet_results = meet_results.append(pandized_event)
    return meet_results

pandize_meet(yr2007).to_csv("IvyData2007.csv")

(2, 500, 'Freestyle')
(3, 200, 'IM')
(4, 50, 'Freestyle')
(5, 1, 'Diving')
(8, 1000, 'Freestyle')
(9, 400, 'IM')
(10, 100, 'Butterfly')
(11, 200, 'Freestyle')
(12, 100, 'Breaststroke')
(13, 100, 'Backstroke')
(15, 1650, 'Freestyle')
(16, 200, 'Backstroke')
(17, 100, 'Freestyle')
(18, 200, 'Breaststroke')
(19, 200, 'Butterfly')
(20, 3, 'Diving')

In [13]:
pandize_meet(yr2008)

(2, 500, 'Freestyle')
(3, 200, 'IM')
(4, 50, 'Freestyle')
(5, 1, 'Diving')
(8, 1000, 'Freestyle')
(9, 400, 'IM')
(10, 100, 'Butterfly')
(11, 200, 'Freestyle')
(12, 100, 'Breaststroke')
(13, 100, 'Backstroke')
(15, 1650, 'Freestyle')
(16, 200, 'Backstroke')
(17, 100, 'Freestyle')
(18, 200, 'Breaststroke')
(19, 200, 'Butterfly')
(20, 3, 'Diving')

,Distance,Ev#,Final,Name,Points,Prelim,Rank,School,Stroke,Yr
0,500,2,4:22.13,"Wollner, Samuel",32,4:22.32,1,Harvard,Freestyle,SR
1,500,2,4:22.17,"Lynch, Eric",28,4:26.45,2,Harvard,Freestyle,JR
2,500,2,4:22.93,"Newman, Wes",27,4:25.10,3,Cornell,Freestyle,JR
3,500,2,4:24.81,"Brunnick, Mason",26,4:26.07,4,Harvard,Freestyle,SO
4,500,2,4:26.09,"Meyer, Alex",25,4:27.06,5,Harvard,Freestyle,SO
5,500,2,4:27.25,"Hunter, Erik",24,4:27.36,6,Navy,Freestyle,FR
6,500,2,4:27.57,"Fee, James",23,4:27.13,7,Pennsylvania,Freestyle,SO
7,500,2,4:27.97,"Volosin, Peter",22,4:27.21,8,Brown,Freestyle,SR
8,500,2,4:27.63,"Lee, Hyun",20,4:30.10,9,Columbia,Freestyle,JR
9,500,2,4:28.77,"Lewkowitz, Blake",17,4:29.22,10,Harvard,Freestyle,FR
10,500,2,4:29.20,"Griest, Robert",16,4:31.06,11,Princeton,Freestyle,JR
11,500,2,4:29.25,"Yntema, Douwe",15,4:30.10,12,Harvard,Freestyle,FR
12,500,2,4:31.26,"Biggs, Pat",14,4:31.20,13,Princeton,Freestyle,FR
13,500,2,4:31.66,"Cousins, Sebastian",13,4:30.29,14,Yale,Freestyle,JR
14,500,2,4:32.53,"Wakefield, Kevin",12,4:29.79,15,Columbia,Freestyle,JR
15,500,2,4:34.65,"Fog, Henning",11,4:31.91,16,Columbia,Freestyle,SR
16,500,2,4:30.66,"Lee, Matt",9,4:33.80,17,Yale,Freestyle,FR
17,500,2,4:31.54,"Kikuchi, Ryan",7,4:34.66,18,Brown,Freestyle,FR
18,500,2,4:32.62,"Lascara, James",6,4:34.92,19,Navy,Freestyle,SO
19,500,2,4:32.90,"Diehl, Porter",5,4:33.08,20,Dartmouth,Freestyle,JR
20,500,2,4:33.12,"Eckel, Dan",4,4:32.74,21,Princeton,Freestyle,JR
21,500,2,4:33.46,"Byzov, Ilya",3,4:34.82,22,Yale,Freestyle,JR
22,500,2,4:34.30,"Buncher, Stan",2,4:34.34,23,Princeton,Freestyle,SR
23,500,2,4:34.33,"McCloskey, Dennen",1,4:33.64,24,Yale,Freestyle,JR
0,200,3,1:45.62,"Rathgeber, Geoff",32,1:47.24,1,Harvard,IM,SR
1,200,3,1:48.57,"Schaffer, Will",28,1:50.25,2,Princeton,IM,JR
2,200,3,1:48.69,"Meyer, Adam",27,1:50.11,3,Navy,IM,SO
3,200,3,1:49.10,"Quemena, Christopher",26,1:49.66,4,Princeton,IM,SO
4,200,3,1:49.98,"Campbell, Nick",25,1:50.18,5,Cornell,IM,SO
5,200,3,1:50.31,"Pagan, Darren",24,1:50.19,6,Columbia,IM,SO
...,...,...,...,...,...,...,...,...,...,...
10,200,19,1:50.23,"Wiese, Jack",16,1:50.70,11,Pennsylvania,Butterfly,SO
11,200,19,1:50.26,"Cohen, Jesse",15,1:50.28,12,Navy,Butterfly,FR
12,200,19,1:50.40,"Alexander, Rich",14,1:50.56,13,Brown,Butterfly,JR
13,200,19,1:51.12,"Brown, Josh",13,1:51.15,14,Columbia,Butterfly,FR
14,200,19,1:51.19,"Keeney, Alex",12,1:51.86,15,Pennsylvania,Butterfly,SR
15,200,19,1:51.74,"Carr, Devon",11,1:50.68,16,Pennsylvania,Butterfly,SR
16,200,19,1:51.51,"Veltman, Patrick",9,1:52.52,17,Navy,Butterfly,FR
17,200,19,1:51.77,"Holcomb, Dean",7,1:52.59,18,Cornell,Butterfly,FR
18,200,19,1:51.98,"Lullo, Brett",6,1:52.18,19,Princeton,Butterfly,FR
19,200,19,1:51.99,"Barron, Nick",5,1:52.78,20,Columbia,Butterfly,SO
20,200,19,1:52.35,"Brotzky, Ilya",4,1:51.91,21,Cornell,Butterfly,SO
21,200,19,1:52.97,"Lascara, James",3,1:53.26,22,Navy,Butterfly,SO
22,200,19,1:53.69,"Woodbury, Drew",2,1:52.16,23,Princeton,Butterfly,SR
23,200,19,1:54.82,"Glenn, Rob",1,1:53.43,24,Brown,Butterfly,SR
0,3,20,33.95,"Speed, Jon",32,80.20,1,Brown,Diving,FR
1,3,20,29.75,"Papageorge, Michael",28,81.85,2,Princeton,Diving,SO
2,3,20,24.00,"Sanders, Luke",27,07.60,3,Harvard,Diving,SR
3,3,20,03.10,"Olson, Olaf",26,11.40,4,Navy,Diving,FR
4,3,20,02.55,"Ranta, Zac",25,83.95,5,Harvard,Diving,FR
5,3,20,93.95,"Dickerson, Dan",24,92.30,6,Princeton,Diving,SO
6,3,20,83.35,"Malcolm, Stuart",23,96.40,7,Princeton,Diving,SR
7,3,20,67.50,"Lichtenstein, Jeff",22,61.70,8,Yale,Diving,SR
8,3,20,18.40,"Berry, Andrew",20,73.10,9,Dartmouth,Diving,SR
9,3,20,99.50,"Donohoe, Chris",17,66.95,10,Cornell,Diving,JR
10,3,20,79.00,"Galinski, Jon",16,72.70,11,Navy,Diving,JR
11,3,20,71.15,"Niekras, Adam",15,73.40,12,Navy,Diving,SR
12,3,20,56.30,"Hehir, Tom",14,44.90,13,Harvard,Diving,JR
13,3,20,53.85,"Hayden, Pat",13,49.85,14,Yale,Diving,SR
14,3,20,49.40,"Sheppard, Mike",12,34.05,15,Cornell,Diving,FR
15,3,20,48.65,"Kambe, C.J.",11,76.85,16,Brown,Diving,SO

In [ ]:
pandize_meet(yr2011).to_csv("IvyData2011.csv")

In [ ]:
pandize_meet(yr2012).to_csv("IvyData2012.csv")

In [14]:
pandize_meet(yr2013)

(2, 500, 'Freestyle')
(3, 200, 'IM')
(4, 50, 'Freestyle')

IndexError: list index out of range

In [ ]:
pandize_meet(yr2014).to_csv("IvyData2014.csv")

In [ ]:
pandize_meet(yr2015).to_csv("IvyData2015.csv")